/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobil;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Anas
 */
public class Geld extends javax.swing.JPanel {

    public static ResultSet rs = null;
    public static PreparedStatement ps;
    /**
     * Creates new form Geld
     */
    public Geld() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        eGeld = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vGeld = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rGeld = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bGeld = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        verkauf = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vkGewin = new javax.swing.JLabel();
        gewinn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(24, 40, 108));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("اجمالي ثمن شراء البضاعة في المخزن");

        eGeld.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eGeld.setForeground(new java.awt.Color(51, 255, 255));
        eGeld.setText("eGeld");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("اجمالي ثمن بيع البضاعة في المخزن");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("ليرة سورية");

        vGeld.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vGeld.setForeground(new java.awt.Color(51, 255, 255));
        vGeld.setText("vGeld");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("ليرة سورية");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("اجمالي ثمن الصيانة");

        rGeld.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rGeld.setForeground(new java.awt.Color(51, 255, 255));
        rGeld.setText("rGeld");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("ليرة سورية");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("اجمالي ثمن المدفوعات");

        bGeld.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bGeld.setForeground(new java.awt.Color(51, 255, 255));
        bGeld.setText("bGeld");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("ليرة سورية");

        jButton1.setText("الرجوع");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("اجمالي ثمن المبيعات");

        verkauf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        verkauf.setForeground(new java.awt.Color(51, 255, 255));
        verkauf.setText("verkauf");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("ليرة سورية");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 102));
        jLabel7.setText("ربح المبيع");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 102));
        jLabel12.setText("الربح الصافي");

        vkGewin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vkGewin.setForeground(new java.awt.Color(51, 204, 255));
        vkGewin.setText("vkGewin");

        gewinn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gewinn.setForeground(new java.awt.Color(51, 204, 255));
        gewinn.setText("gewinn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vkGewin)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(322, 322, 322)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(gewinn)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12)
                        .addGap(178, 178, 178)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vGeld)
                                    .addComponent(eGeld))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verkauf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rGeld, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(44, 44, 44)
                                .addComponent(bGeld)))))
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eGeld)
                    .addComponent(jLabel3))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vGeld)
                    .addComponent(jLabel5))
                .addGap(65, 65, 65)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(verkauf)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(vkGewin))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rGeld)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bGeld)
                    .addComponent(jLabel11))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(gewinn))
                        .addGap(50, 50, 50))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Mobil.cl.show(Mobil.cardPanel, "Liste");
    }//GEN-LAST:event_jButton1ActionPerformed
public static void ekZeigen(){
    String query1="SELECT SUM(kaufpreise*quan) as s FROM kaufware";
        try {
            ps = Utils.getConnection().prepareStatement(query1);
            rs=ps.executeQuery();
            while(rs.next()){
               eGeld.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public static void vkZeigen(){
    String query="SELECT SUM(a.vkpreise*k.quan)as s FROM kaufware k,ware a WHERE k.wareId=a.ID";
        try {
            ps = Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
               vGeld.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public static void verkaufZeigen(){
    String query="SELECT SUM(w.vkpreise*Menge)as s FROM `rechnungxware`,ware w WHERE w.ID=rechnungxware.wareID";
        try {
            ps = Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
               verkauf.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public static void verkaufGewinn(){
    String query="SELECT SUM((w.vkpreise*r.Menge)-(k.kaufpreise*r.Menge))as s FROM rechnungxware r,ware w ,kaufware k WHERE w.ID=r.wareID AND r.wareID=k.wareId";
        try {
            ps=Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
                vkGewin.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public static void rkZeigen(){
    String query="SELECT SUM(geld) as s FROM `rebaratur`";
        try {
            ps = Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
               rGeld.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public static void bkZeigen(){
    String query="SELECT SUM(geld) as s FROM betzahlt";
        try {
            ps = Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
               bGeld.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public static void gewinn(){
double vkG=Double.parseDouble(vkGewin.getText());
double reparaturG=Double.parseDouble(rGeld.getText());
double bezahlG=Double.parseDouble(bGeld.getText());
double summ=(vkG+reparaturG)-bezahlG;
gewinn.setText(Double.toString(summ));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel bGeld;
    public static javax.swing.JLabel eGeld;
    private static javax.swing.JLabel gewinn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JLabel rGeld;
    private static javax.swing.JLabel vGeld;
    private static javax.swing.JLabel verkauf;
    private static javax.swing.JLabel vkGewin;
    // End of variables declaration//GEN-END:variables
}
