/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobil;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Anas
 */
public class Geld extends javax.swing.JPanel {

    public static ResultSet rs = null;
    public static PreparedStatement ps;
    /**
     * Creates new form Geld
     */
    public Geld() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        eGeld = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vGeld = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rGeld = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bGeld = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        verkauf = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(24, 40, 108));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("اجمالي ثمن شراء البضاعة في المخزن");

        eGeld.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eGeld.setForeground(new java.awt.Color(51, 255, 255));
        eGeld.setText("eGeld");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("اجمالي ثمن بيع البضاعة في المخزن");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("ليرة سورية");

        vGeld.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vGeld.setForeground(new java.awt.Color(51, 255, 255));
        vGeld.setText("vGeld");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("ليرة سورية");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("اجمالي ثمن الصيانة");

        rGeld.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rGeld.setForeground(new java.awt.Color(51, 255, 255));
        rGeld.setText("rGeld");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("ليرة سورية");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("اجمالي ثمن المدفوعات");

        bGeld.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bGeld.setForeground(new java.awt.Color(51, 255, 255));
        bGeld.setText("bGeld");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("ليرة سورية");

        jButton1.setText("الرجوع");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("اجمالي ثمن المبيعات");

        verkauf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        verkauf.setForeground(new java.awt.Color(51, 255, 255));
        verkauf.setText("verkauf");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("ليرة سورية");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eGeld)
                                .addComponent(bGeld, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(vGeld)
                            .addComponent(rGeld)
                            .addComponent(verkauf))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(159, 159, 159))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(235, 235, 235))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eGeld)
                    .addComponent(jLabel3))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vGeld)
                    .addComponent(jLabel5))
                .addGap(65, 65, 65)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(verkauf)
                    .addComponent(jLabel10))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rGeld)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bGeld)
                    .addComponent(jLabel11))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Mobil.cl.show(Mobil.cardPanel, "Liste");
    }//GEN-LAST:event_jButton1ActionPerformed
public static void ekZeigen(){
    String query="SELECT SUM(`Kaufpreis`*quantitaet) as s FROM `ware`";
        try {
            ps = Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
               eGeld.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public static void vkZeigen(){
    String query="SELECT SUM(Verkaufprise*quantitaet)as s FROM `ware`";
        try {
            ps = Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
               vGeld.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public static void verkaufZeigen(){
    String query="SELECT SUM(Verkaufprise*Menge)as s FROM `rechnungxware`,ware WHERE ware.ID=rechnungxware.wareID";
        try {
            ps = Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
               verkauf.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public static void rkZeigen(){
    String query="SELECT SUM(geld) as s FROM `rebaratur`";
        try {
            ps = Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
               rGeld.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
public static void bkZeigen(){
    String query="SELECT SUM(geld) as s FROM betzahlt";
        try {
            ps = Utils.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
               bGeld.setText(rs.getString("s"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Geld.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel bGeld;
    private static javax.swing.JLabel eGeld;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JLabel rGeld;
    private static javax.swing.JLabel vGeld;
    private static javax.swing.JLabel verkauf;
    // End of variables declaration//GEN-END:variables
}
