/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobil;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anas
 */
public class JahresÜbersicht extends javax.swing.JPanel {

    static PreparedStatement ps;
    static ResultSet st;
    static DefaultTableModel model;

    /**
     * Creates new form JahresÜbersicht
     */
    public JahresÜbersicht() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, "الشهر  1"},
                {null, null, null, "الشهر 2"},
                {null, null, null, "الشهر 3"},
                {null, null, null, "الشهر 4"},
                {null, null, null, "الشهر 5"},
                {null, null, null, "الشهر  6"},
                {null, null, null, "الشهر 7"},
                {null, null, null, "الشهر 8"},
                {null, null, null, "الشهر 9"},
                {null, null, null, "الشهر 10"},
                {null, null, null, "الشهر 11"},
                {null, null, null, "الشهر 12"}
            },
            new String [] {
                "الربح او الخسارة", "الخارج", "الداخل", "الاشهر"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void eingang() {
        String query = "SELECT SUM(abrechnung.gesamt)\n"
                + "FROM abrechnung where MONTH(abrechnung.datum)=?";
                
        try {
            ps = Utils.getConnection().prepareStatement(query);
            
            for(int i=0;i<12;i++){
                ps.setInt(1,i+1);
                     st = ps.executeQuery();  
                 }
          
             
        } catch (SQLException ex) {
            Logger.getLogger(JahresÜbersicht.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
